export const METADATA_GOOGLE_OBJ = [
  {
    LibraryID: 'LIB01',
    SampleName: 'SAMIDA-EXTSAMA',
    SampleID: 'SAMIDA',
    ExternalSampleID: '',
    SubjectID: 'SUBIDA',
    ExternalSubjectID: 'EXTSUBIDA',
    Phenotype: '',
    Quality: '',
    Source: 'FFPE',
    ProjectName: 'MyPath',
    ProjectOwner: 'Alice',
    ExperimentID: 'Exper1',
    Type: 'WTS',
    Assay: 'NebRNA',
    OverrideCycles: 'Y151;I8;I8;Y151',
    Workflow: 'clinical',
    'Coverage (X)': '6.0',
    'TruSeq Index, unless stated': 'Neb2-F07',
    'Run#': 'P30',
    Comments: '',
    rRNA: undefined,
    'qPCR ID': '#NAME?',
    'Sample_ID (SampleSheet)': 'SAMIDA_LIB01',
  },
  {
    LibraryID: 'LIB02',
    SampleName: 'SAMIDB-EXTSAMB',
    SampleID: 'SAMIDB',
    ExternalSampleID: 'EXTSAMB',
    SubjectID: 'SUBIDB',
    ExternalSubjectID: 'EXTSUBIDB',
    Phenotype: 'tumor',
    Quality: 'poor',
    Source: 'FFPE',
    ProjectName: 'Fake',
    ProjectOwner: 'Bob',
    ExperimentID: 'Exper1',
    Type: 'WTS',
    Assay: 'NebRNA',
    OverrideCycles: 'Y151;I8;I8;Y151',
    Workflow: 'clinical',
    'Coverage (X)': '6.3',
    'TruSeq Index, unless stated': 'Neb2-G07',
    'Run#': 'P30',
    Comments: '',
    rRNA: undefined,
    'qPCR ID': '#NAME?',
    'Sample_ID (SampleSheet)': 'SAMIDB_LIB02',
  },
  {
    LibraryID: 'LIB03',
    SampleName: 'SAMIDB-EXTSAMB',
    SampleID: 'SAMIDB',
    ExternalSampleID: 'EXTSAMB',
    SubjectID: 'SUBIDB',
    ExternalSubjectID: 'EXTSUBIDB',
    Phenotype: 'tumor',
    Quality: 'poor',
    Source: 'FFPE',
    ProjectName: 'Fake',
    ProjectOwner: 'Bob',
    ExperimentID: 'Exper1',
    Type: 'WTS',
    Assay: 'NebRNA',
    OverrideCycles: 'Y151;I8;I8;Y151',
    Workflow: 'clinical',
    'Coverage (X)': '6.0',
    'TruSeq Index, unless stated': 'Neb2-H07',
    'Run#': 'P30',
    Comments: '',
    rRNA: undefined,
    'qPCR ID': '#NAME?',
    'Sample_ID (SampleSheet)': 'SAMIDB_LIB03',
  },
  {
    LibraryID: 'LIB04',
    SampleName: 'SAMIDA-EXTSAMA',
    SampleID: 'SAMIDA',
    ExternalSampleID: 'EXTSAMA',
    SubjectID: 'SUBIDA',
    ExternalSubjectID: 'EXTSUBIDA',
    Phenotype: 'tumor',
    Quality: 'poor',
    Source: 'FFPE',
    ProjectName: 'MyPath',
    ProjectOwner: 'Alice',
    ExperimentID: 'Exper1',
    Type: 'WTS',
    Assay: 'NebRNA',
    OverrideCycles: 'Y151;I8;I8;Y151',
    Workflow: 'clinical',
    'Coverage (X)': '6.0',
    'TruSeq Index, unless stated': 'Neb2-F07',
    'Run#': 'P30',
    Comments: '',
    rRNA: '',
    'qPCR ID': '#NAME?',
    'Sample_ID (SampleSheet)': 'SAMIDA_LIB01',
  },
];
