# An image with our added services
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Packages
    init: |
      pre-commit install
      pre-commit run
      yarn install
      find ./lib -name 'requirements.txt' -exec pip install -r {} \;
      pip install -r requirements-dev.txt
      docker compose pull

  - name: Mock Services
    command: |
      docker compose up 

ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-browser

  - name: Database UI
    description: Port 10700 for the frontend
    port: 10700
