repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        exclude: ^(yarn.lock|.yarn/)
#      - id: check-json
#      - id: check-yaml
#      - id: detect-aws-credentials
      - id: detect-private-key
#      - id: end-of-file-fixer
#      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [ --branch, main, --branch, master, --pattern, release/.* ]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: detect secrets
        args: [ '--baseline', '.secrets.baseline' ]
        exclude: ^(yarn.lock|.yarn/|.yarnrc.yml)

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.17.0
    hooks:
      - id: eslint
        exclude: ^(skel/|yarn.lock|.yarn/|.local/|docs/|openapi/)

  # FIXME: plugin repo is public archived. To follow up for replacement. ~victor
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        entry: yarn prettier --ignore-unknown
        args: [ '--check' ]
        exclude: ^(skel/|yarn.lock|.yarn/|.local/|docs/|openapi/)
