//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum::FromRepr,
    strum::EnumCount,
    sqlx::Decode,
    sqlx::Encode,
    utoipa::ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "archive_status")]
pub enum ArchiveStatus {
    #[sea_orm(string_value = "ArchiveAccess")]
    ArchiveAccess,
    #[sea_orm(string_value = "DeepArchiveAccess")]
    DeepArchiveAccess,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum::FromRepr,
    strum::EnumCount,
    sqlx::Decode,
    sqlx::Encode,
    utoipa::ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "crawl_status")]
pub enum CrawlStatus {
    #[sea_orm(string_value = "Completed")]
    Completed,
    #[sea_orm(string_value = "Failed")]
    Failed,
    #[sea_orm(string_value = "InProgress")]
    InProgress,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum::FromRepr,
    strum::EnumCount,
    sqlx::Decode,
    sqlx::Encode,
    utoipa::ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "event_type")]
pub enum EventType {
    #[sea_orm(string_value = "Created")]
    Created,
    #[sea_orm(string_value = "Deleted")]
    Deleted,
    #[sea_orm(string_value = "Other")]
    Other,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum::FromRepr,
    strum::EnumCount,
    sqlx::Decode,
    sqlx::Encode,
    utoipa::ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "reason")]
pub enum Reason {
    #[sea_orm(string_value = "Crawl")]
    Crawl,
    #[sea_orm(string_value = "CrawlRestored")]
    CrawlRestored,
    #[sea_orm(string_value = "CreatedCompleteMultipartUpload")]
    CreatedCompleteMultipartUpload,
    #[sea_orm(string_value = "CreatedCopy")]
    CreatedCopy,
    #[sea_orm(string_value = "CreatedPost")]
    CreatedPost,
    #[sea_orm(string_value = "CreatedPut")]
    CreatedPut,
    #[sea_orm(string_value = "Deleted")]
    Deleted,
    #[sea_orm(string_value = "DeletedLifecycle")]
    DeletedLifecycle,
    #[sea_orm(string_value = "RestoreExpired")]
    RestoreExpired,
    #[sea_orm(string_value = "Restored")]
    Restored,
    #[sea_orm(string_value = "StorageClassChanged")]
    StorageClassChanged,
    #[sea_orm(string_value = "Unknown")]
    Unknown,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum::FromRepr,
    strum::EnumCount,
    sqlx::Decode,
    sqlx::Encode,
    utoipa::ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "storage_class")]
pub enum StorageClass {
    #[sea_orm(string_value = "DeepArchive")]
    DeepArchive,
    #[sea_orm(string_value = "Glacier")]
    Glacier,
    #[sea_orm(string_value = "GlacierIr")]
    GlacierIr,
    #[sea_orm(string_value = "IntelligentTiering")]
    IntelligentTiering,
    #[sea_orm(string_value = "OnezoneIa")]
    OnezoneIa,
    #[sea_orm(string_value = "Outposts")]
    Outposts,
    #[sea_orm(string_value = "ReducedRedundancy")]
    ReducedRedundancy,
    #[sea_orm(string_value = "Snow")]
    Snow,
    #[sea_orm(string_value = "Standard")]
    Standard,
    #[sea_orm(string_value = "StandardIa")]
    StandardIa,
}
