# Generated by Django 5.1.2 on 2024-12-04 11:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "orcabus_id",
                    models.CharField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_orcabus_id",
                                message="ULID is expected to be 26 characters long",
                                regex="^[\\w]{26}$",
                            )
                        ],
                    ),
                ),
                ("comment", models.TextField()),
                ("association_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "orcabus_id",
                    models.CharField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_orcabus_id",
                                message="ULID is expected to be 26 characters long",
                                regex="^[\\w]{26}$",
                            )
                        ],
                    ),
                ),
                ("instrument_run_id", models.CharField(max_length=255, unique=True)),
                ("run_volume_name", models.TextField()),
                ("run_folder_path", models.TextField()),
                ("run_data_uri", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("FAILED", "Failed"),
                            ("SUCCEEDED", "Succeeded"),
                            ("ABORTED", "Aborted"),
                        ],
                        max_length=255,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "reagent_barcode",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "flowcell_barcode",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sample_sheet_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sequence_run_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sequence_run_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("v1pre3_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ica_project_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("api_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("run_folder_path__isnull", False),
                            models.Q(
                                ("api_url__isnull", False),
                                ("ica_project_id__isnull", False),
                                ("v1pre3_id__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="check_run_folder_path_or_bssh_keys_not_null",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "orcabus_id",
                    models.CharField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_orcabus_id",
                                message="ULID is expected to be 26 characters long",
                                regex="^[\\w]{26}$",
                            )
                        ],
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="sequence_run_manager.sequence",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
