# Generated by Django 5.0.5 on 2024-06-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sequence_run_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequence",
            name="status",
            field=models.CharField(
                choices=[
                    ("STARTED", "Started"),
                    ("FAILED", "Failed"),
                    ("SUCCEEDED", "Succeeded"),
                    ("ABORTED", "Aborted"),
                ],
                max_length=255,
            ),
        ),
    ]
