# Generated by Django 5.1.2 on 2024-12-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sequence_run_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequence",
            name="run_folder_path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
