# Generated by Django 5.1.4 on 2025-03-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sequence_run_manager", "0005_sequence_experiment_name_libraryassociation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequence",
            name="instrument_run_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="sample_sheet_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="sequence_run_id",
            field=models.CharField(max_length=255),
        ),
    ]
