# Generated by Django 5.1.4 on 2025-03-06 22:19

import django.db.models.deletion
import sequence_run_manager.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sequence_run_manager", "0006_alter_sequence_instrument_run_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleSheet",
            fields=[
                (
                    "orcabus_id",
                    sequence_run_manager.fields.OrcaBusIdField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("sample_sheet_name", models.CharField(max_length=255)),
                (
                    "association_status",
                    models.CharField(default="active", max_length=255),
                ),
                ("association_timestamp", models.DateTimeField(auto_now_add=True)),
                ("sample_sheet_content", models.JSONField(blank=True, null=True)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sequence_run_manager.sequence",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
