import { Construct } from 'constructs';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as ssm from 'aws-cdk-lib/aws-ssm';
import * as events from 'aws-cdk-lib/aws-events';
import * as secretsManager from 'aws-cdk-lib/aws-secretsmanager';
import { WorkflowDraftRunStateChangeToWorkflowRunStateChangeReadyConstruct } from '../../../../../../../components/event-workflowdraftrunstatechange-to-workflowrunstatechange-ready';

/*
Part 2

* Input Event source: `orcabus.bsshfastqcopyinputeventglue`
* Input Event DetailType: `WorkflowDraftRunStateChange`
* Input Event status: `draft`

* Output Event source: `orcabus.bsshfastqcopyinputeventglue`
* Output Event DetailType: `WorkflowRunStateChange`
* Output Event status: `ready`

* The BsshFastqCopyManagerDraftToReadyMaker Construct
  * Subscribes to the draft events generated by this stack
  * Pushes an event payload of the input for the BSSH Fastq Copy Object
*/

export interface bsshFastqCopyManagerDraftToReadyMakerConstructProps {
  tableObj: dynamodb.ITableV2;
  outputUriSsmParameterObj: ssm.IStringParameter;
  eventBusObj: events.IEventBus;
  icav2AccessTokenSecretObj: secretsManager.ISecret;
}

export class BsshFastqCopyManagerDraftToReadyMakerConstruct extends Construct {
  public readonly bsshFastqCopyManagerDraftToReadyMakerEventMap = {
    prefix: 'elmer-bssh-fastq-copy',
    tablePartition: 'bssh_fastq_copy',
    triggerSource: 'orcabus.bsshfastqcopyinputeventglue',
    triggerStatus: 'draft',
    triggerDetailType: 'WorkflowDraftRunStateChange',
    outputSource: 'orcabus.bsshfastqcopyinputeventglue',
    outputStatus: 'ready',
    payloadVersion: '2024.05.24',
    workflowName: 'bsshFastqCopy',
    workflowVersion: '2024.05.24',
  };

  constructor(
    scope: Construct,
    id: string,
    props: bsshFastqCopyManagerDraftToReadyMakerConstructProps
  ) {
    super(scope, id);

    /*
    Part 1: Initialise the workflow draft run state change to workflow run state change construct
    */
    new WorkflowDraftRunStateChangeToWorkflowRunStateChangeReadyConstruct(
      this,
      'bssh_fastq_copy_manager_input_maker_external',
      {
        /*
        Set Input StateMachine Object
        */
        lambdaPrefix: this.bsshFastqCopyManagerDraftToReadyMakerEventMap.prefix,
        payloadVersion: this.bsshFastqCopyManagerDraftToReadyMakerEventMap.payloadVersion,
        stateMachinePrefix: this.bsshFastqCopyManagerDraftToReadyMakerEventMap.prefix,

        /*
        Table objects
        */
        tableObj: props.tableObj,
        tablePartitionName: this.bsshFastqCopyManagerDraftToReadyMakerEventMap.tablePartition,

        /*
        Event Triggers
        */
        eventBusObj: props.eventBusObj,
        triggerSource: this.bsshFastqCopyManagerDraftToReadyMakerEventMap.triggerSource,
        triggerStatus: this.bsshFastqCopyManagerDraftToReadyMakerEventMap.triggerStatus,

        /*
        Event Outputs
        */
        workflowName: this.bsshFastqCopyManagerDraftToReadyMakerEventMap.workflowName,
        workflowVersion: this.bsshFastqCopyManagerDraftToReadyMakerEventMap.workflowVersion,
        outputSource: this.bsshFastqCopyManagerDraftToReadyMakerEventMap.outputSource,

        /*
        Set the output uri
        */
        outputUriSsmParameterObj: props.outputUriSsmParameterObj,

        /*
        ICAv2 Secret Construct
        */
        icav2AccessTokenSecretObj: props.icav2AccessTokenSecretObj,
      }
    );
  }
}
