# Generated by Django 5.1.2 on 2024-10-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcontact',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalindividual',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallibrary',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsample',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsubject',
            name='history_user',
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='history_user_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalindividual',
            name='history_user_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallibrary',
            name='history_user_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='history_user_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='history_user_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubject',
            name='history_user_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
