# Generated by Django 5.1 on 2024-09-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalspecimen',
            old_name='specimen_id',
            new_name='lab_specimen_id',
        ),
        migrations.RenameField(
            model_name='historicalsubject',
            old_name='subject_id',
            new_name='lab_subject_id',
        ),
        migrations.RenameField(
            model_name='specimen',
            old_name='specimen_id',
            new_name='lab_specimen_id',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_id',
            new_name='lab_subject_id',
        ),
        migrations.AddField(
            model_name='historicalspecimen',
            name='external_specimen_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubject',
            name='external_subject_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='external_specimen_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='external_subject_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
