# Generated by Django 5.0.3 on 2024-07-11 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_historicallibrary_coverage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='subjects',
        ),
        migrations.AddField(
            model_name='historicalspecimen',
            name='subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.subject'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subject'),
        ),
        migrations.DeleteModel(
            name='HistoricalSpecimen_subjects',
        ),
    ]
