# Generated by Django 5.1.4 on 2025-01-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_contact_orcabus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallibrary',
            name='override_cycles',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='override_cycles',
            field=models.CharField(blank=True, null=True),
        ),
    ]
