test:
	@check-jsonschema --schemafile PayloadDataReady.schema.json example/PayloadDataReady__example1.json
	@check-jsonschema --schemafile PayloadDataSucceeded.schema.json example/PayloadDataSucceeded__example1.json
