services:
  db:
    # Use version that align with upper bound of AWS Aurora PostgreSQL LTS
    # https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Updates.LTS.html
    # See container image doc https://gallery.ecr.aws/docker/library/postgres for more settings
    image: public.ecr.aws/docker/library/postgres:16
    container_name: orcabus_db
    restart: always
    environment:
      - POSTGRES_DB=orcabus
      - POSTGRES_USER=orcabus
      - POSTGRES_PASSWORD=orcabus
    ports:
      - '5432:5432'
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d orcabus -U orcabus']
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 90s
