test:
	@check-jsonschema --schemafile SequenceRunStateChange.schema.json example/SRSC__started.json
	@check-jsonschema --schemafile SequenceRunStateChange.schema.json example/SRSC__succeeded.json
	@check-jsonschema --schemafile SequenceRunSampleSheetChange.schema.json example/SRSSC.json
	@check-jsonschema --schemafile SequenceRunLibraryLinkingChange.schema.json example/SRLLC.json
