#!/usr/bin/env python3

"""
Read the contents of the ICAv2 file (which will just contain the md5sum contents generated by the ECS task
"""


# Imports
from wrapica.project_data import (
    read_icav2_file_contents_to_string,
    convert_uri_to_project_data_obj,
    ProjectData
)
import boto3
from os import environ


# AWS things
def get_ssm_client() -> 'SSMClient':
    """
    Return SSM client
    """
    return boto3.client("ssm")


def get_secrets_manager_client() -> 'SecretsManagerClient':
    """
    Return Secrets Manager client
    """
    return boto3.client("secretsmanager")


def get_ssm_parameter_value(parameter_path) -> str:
    """
    Get the ssm parameter value from the parameter path
    :param parameter_path:
    :return:
    """
    return get_ssm_client().get_parameter(Name=parameter_path)["Parameter"]["Value"]


def get_secret(secret_arn: str) -> str:
    """
    Return secret value
    """
    return get_secrets_manager_client().get_secret_value(SecretId=secret_arn)["SecretString"]


# Set the icav2 environment variables
def set_icav2_env_vars():
    """
    Set the icav2 environment variables
    :return:
    """
    environ["ICAV2_BASE_URL"] = "https://ica.illumina.com/ica/rest"
    environ["ICAV2_ACCESS_TOKEN"] = get_secret(
        environ["ICAV2_ACCESS_TOKEN_SECRET_ID"]
    )


def handler(event, context):
    """
    Takes in a filename and returns the contents of the file as a string
    :param event:
    :param context:
    :return:
    """
    # Set ICAv2 env vars
    set_icav2_env_vars()

    # Read the ICAv2 file contents
    file_uri = event['file_uri']

    # Read in the file uri as a project data id
    projectdata_obj: ProjectData = convert_uri_to_project_data_obj(file_uri)

    return {
        "file_contents": read_icav2_file_contents_to_string(
            projectdata_obj.project_id,
            projectdata_obj.data.id
        ).strip()
    }


# if __name__ == "__main__":
#     import json
#     environ["ICAV2_ACCESS_TOKEN_SECRET_ID"] = "ICAv2JWTKey-umccr-prod-service-dev"
#     environ["AWS_PROFILE"] = "umccr-development"
#
#     print(
#         json.dumps(
#             handler(
#                 {
#                     "file_uri": "s3://pipeline-dev-cache-503977275616-ap-southeast-2/byob-icav2/development/cache/ora-compression/20241119abcd1234/TGACGAAT.GCCTACTG.4.L2401553.241024_A00130_0336_BHW7MVDSXC/R2.md5sum.txt"
#                 },
#                 None
#             ),
#             indent=4
#         )
#     )
#
#     # {
#     #     "file_contents": "8f5c4a1039a1c873878661846b1f61a3"  # pragma: allowlist secret
#     # }
