# Generated by Django 4.2.1 on 2023-06-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("instrument_run_id", models.CharField(max_length=255, unique=True)),
                ("run_volume_name", models.TextField()),
                ("run_folder_path", models.TextField()),
                ("run_data_uri", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("failed", "Failed"),
                            ("succeeded", "Succeeded"),
                            ("aborted", "Aborted"),
                        ],
                        max_length=255,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "reagent_barcode",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "flowcell_barcode",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sample_sheet_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sequence_run_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sequence_run_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
