#!/usr/bin/env python3

import re

# Add context prefix
CONTEXT_PREFIX = "fqr"

# https://regex101.com/r/zJRC62/1
ORCABUS_ULID_REGEX_MATCH = re.compile(r'^[a-z0-9]{3}\.[A-Z0-9]{26}$')

GET_LIBRARY_ORCABUS_ID_FROM_LIBRARY_ID_LAMBDA_FUNCTION_ARN_ENV_VAR = 'GET_LIBRARY_ORCABUS_ID_FROM_LIBRARY_ID_FASTQ_MANAGER_ARN'
GET_LIBRARY_ID_FROM_LIBRARY_ORCABUS_ID_LAMBDA_FUNCTION_ARN_ENV_VAR = 'GET_LIBRARY_ID_FROM_LIBRARY_ORCABUS_ID_FASTQ_MANAGER_ARN'
GET_PRESIGNED_URL_FROM_S3_INGEST_ID_LAMBDA_FUNCTION_ARN_ENV_VAR = 'GET_PRESIGNED_URL_FROM_S3_INGEST_ID_FASTQ_MANAGER_ARN'
GET_S3_INGEST_ID_FROM_S3_URI_LAMBDA_FUNCTION_ARN_ENV_VAR = 'GET_S3_INGEST_ID_FROM_S3_URI_FASTQ_MANAGER_ARN'
GET_S3_URI_FROM_S3_INGEST_ID_LAMBDA_FUNCTION_ARN_ENV_VAR = 'GET_S3_URI_FROM_S3_INGEST_ID_FASTQ_MANAGER_ARN'