#!/usr/bin/env python3

import re
from enum import Enum

# Add context prefix - fastq list row
FQLR_CONTEXT_PREFIX = "fqr"  # Fastq List Row
FQS_CONTEXT_PREFIX = "fqs"  # Fastq Set
FQLR_JOB_PREFIX = "fqj"  # Fastq Job Prefix

# https://regex101.com/r/zJRC62/1
ORCABUS_ULID_REGEX_MATCH = re.compile(r'^[a-z0-9]{3}\.[A-Z0-9]{26}$')

RUN_QC_STATS_AWS_STEP_FUNCTION_ARN_ENV_VAR = "QC_STATS_AWS_STEP_FUNCTION_ARN"
RUN_NTSM_COUNT_AWS_STEP_FUNCTION_ARN_ENV_VAR = "NTSM_COUNT_AWS_STEP_FUNCTION_ARN"
RUN_NTSM_EVAL_X_AWS_STEP_FUNCTION_ARN_ENV_VAR = "NTSM_EVAL_X_AWS_STEP_FUNCTION_ARN"
RUN_NTSM_EVAL_X_Y_AWS_STEP_FUNCTION_ARN_ENV_VAR = "NTSM_EVAL_X_Y_AWS_STEP_FUNCTION_ARN"
RUN_FILE_COMPRESSION_AWS_STEP_FUNCTION_ARN_ENV_VAR = "FILE_COMPRESSION_AWS_STEP_FUNCTION_ARN"

DEFAULT_ROWS_PER_PAGE = 100

# Envs
EVENT_BUS_NAME_ENV_VAR = "EVENT_BUS_NAME"
EVENT_SOURCE_ENV_VAR = "EVENT_SOURCE"
EVENT_DETAIL_TYPE_FASTQ_LIST_ROW_STATE_CHANGE_ENV_VAR = "EVENT_DETAIL_TYPE_FASTQ_LIST_ROW_STATE_CHANGE"
EVENT_DETAIL_TYPE_FASTQ_SET_STATE_CHANGE_ENV_VAR = "EVENT_DETAIL_TYPE_FASTQ_SET_ROW_STATE_CHANGE"

# Add status to events
class FastqListRowStateChangeStatusEventsEnum(Enum):
    FASTQ_LIST_ROW_CREATED = "FASTQ_LIST_ROW_CREATED"
    FASTQ_LIST_ROW_DELETED = "FASTQ_LIST_ROW_DELETED"
    READ_SET_ADDED = "READ_SET_ADDED"
    READ_SET_DELETED = "READ_SET_DELETED"
    FILE_COMPRESSION_UPDATED = "FILE_COMPRESSION_UPDATED"
    QC_UPDATED = "QC_UPDATED"
    NTSM_UPDATED = "NTSM_UPDATED"
    READ_COUNT_UPDATED = "READ_COUNT_UPDATED"
    LIBRARY_UPDATED = "LIBRARY_UPDATED"
    FASTQ_LIST_ROW_IS_VALID = "FASTQ_LIST_ROW_IS_VALID"
    FASTQ_LIST_ROW_IS_INVALID = "FASTQ_LIST_ROW_IS_INVALID"
    FASTQ_LIST_ROW_SET_UPDATED = "FASTQ_LIST_ROW_SET_UPDATED"



# Add status to fastq set events
class FastqSetStateChangeStatusEventsEnum(Enum):
    FASTQ_SET_CREATED = "FASTQ_SET_CREATED"
    FASTQ_SET_DELETED = "FASTQ_SET_DELETED"
    FASTQ_LIST_ROW_LINKED = "FASTQ_LIST_ROW_LINKED"
    FASTQ_LIST_ROW_UNLINKED = "FASTQ_LIST_ROW_UNLINKED"
    FASTQ_SET_IS_CURRENT = "FASTQ_SET_IS_CURRENT"
    FASTQ_SET_IS_NOT_CURRENT = "FASTQ_SET_IS_NOT_CURRENT"
    FASTQ_SET_ADDITIONAL_FASTQS_ALLOWED = "FASTQ_SET_ADDITIONAL_FASTQS_ALLOWED"
    FASTQ_SET_ADDITIONAL_FASTQS_DISALLOWED = "FASTQ_SET_ADDITIONAL_FASTQS_DISALLOWED"
    FASTQ_SET_MERGED = "FASTQ_SET_MERGED"
