#!/usr/bin/env python3

import re
from enum import Enum
from os import environ

# Add context prefix - fastq list row
FQLR_CONTEXT_PREFIX = "fqr"  # Fastq List Row
FQS_CONTEXT_PREFIX = "fqs"  # Fastq Set
FQLR_JOB_PREFIX = "fqj"  # Fastq Job Prefix

# https://regex101.com/r/zJRC62/1
ORCABUS_ULID_REGEX_MATCH = re.compile(r'^[a-z0-9]{3}\.[A-Z0-9]{26}$')

RUN_QC_STATS_AWS_STEP_FUNCTION_ARN_ENV_VAR = "QC_STATS_AWS_STEP_FUNCTION_ARN"
RUN_NTSM_COUNT_AWS_STEP_FUNCTION_ARN_ENV_VAR = "NTSM_COUNT_AWS_STEP_FUNCTION_ARN"
RUN_NTSM_EVAL_X_AWS_STEP_FUNCTION_ARN_ENV_VAR = "NTSM_EVAL_X_AWS_STEP_FUNCTION_ARN"
RUN_NTSM_EVAL_X_Y_AWS_STEP_FUNCTION_ARN_ENV_VAR = "NTSM_EVAL_X_Y_AWS_STEP_FUNCTION_ARN"
RUN_FILE_COMPRESSION_AWS_STEP_FUNCTION_ARN_ENV_VAR = "FILE_COMPRESSION_AWS_STEP_FUNCTION_ARN"

DEFAULT_ROWS_PER_PAGE = 100

# Envs
EVENT_BUS_NAME_ENV_VAR = "EVENT_BUS_NAME"
EVENT_SOURCE_ENV_VAR = "EVENT_SOURCE"
EVENT_DETAIL_TYPE_CREATE_FASTQ_LIST_ROW_ENV_VAR = "EVENT_DETAIL_TYPE_CREATE_FASTQ_LIST_ROW"
EVENT_DETAIL_TYPE_UPDATE_FASTQ_LIST_ROW_ENV_VAR = "EVENT_DETAIL_TYPE_UPDATE_FASTQ_LIST_ROW"
EVENT_DETAIL_TYPE_DELETE_FASTQ_LIST_ROW_ENV_VAR = "EVENT_DETAIL_TYPE_DELETE_FASTQ_LIST_ROW"
EVENT_DETAIL_TYPE_CREATE_FASTQ_SET_ENV_VAR = "EVENT_DETAIL_TYPE_CREATE_FASTQ_SET"
EVENT_DETAIL_TYPE_UPDATE_FASTQ_SET_ENV_VAR = "EVENT_DETAIL_TYPE_UPDATE_FASTQ_SET"
EVENT_DETAIL_TYPE_MERGE_FASTQ_SET_ENV_VAR = "EVENT_DETAIL_TYPE_MERGE_FASTQ_SET"
EVENT_DETAIL_TYPE_DELETE_FASTQ_SET_ENV_VAR = "EVENT_DETAIL_TYPE_DELETE_FASTQ_SET"



# Event enums
class FastqListRowEventDetailTypeEnum(Enum):
    CREATE = environ[EVENT_DETAIL_TYPE_CREATE_FASTQ_LIST_ROW_ENV_VAR]
    UPDATE = environ[EVENT_DETAIL_TYPE_UPDATE_FASTQ_LIST_ROW_ENV_VAR]
    DELETE = environ[EVENT_DETAIL_TYPE_DELETE_FASTQ_LIST_ROW_ENV_VAR]


class FastqSetEventDetailTypeEnum(Enum):
    CREATE = environ[EVENT_DETAIL_TYPE_CREATE_FASTQ_SET_ENV_VAR]
    UPDATE = environ[EVENT_DETAIL_TYPE_UPDATE_FASTQ_SET_ENV_VAR]
    MERGE = environ[EVENT_DETAIL_TYPE_MERGE_FASTQ_SET_ENV_VAR]
    DELETE = environ[EVENT_DETAIL_TYPE_DELETE_FASTQ_SET_ENV_VAR]

