# Generated by Django 5.1 on 2024-08-21 05:48

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('orcabus_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('library_id', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payload_ref_id', models.CharField(max_length=255, unique=True)),
                ('version', models.CharField(max_length=255)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LibraryAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_date', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_manager.library')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('workflow_name', models.CharField(max_length=255)),
                ('workflow_version', models.CharField(max_length=255)),
                ('execution_engine', models.CharField(max_length=255)),
                ('execution_engine_pipeline_id', models.CharField(max_length=255)),
                ('approval_state', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('workflow_name', 'workflow_version')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('portal_run_id', models.CharField(max_length=255, unique=True)),
                ('execution_id', models.CharField(blank=True, max_length=255, null=True)),
                ('workflow_run_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('libraries', models.ManyToManyField(through='workflow_manager.LibraryAssociation', to='workflow_manager.library')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_manager.workflow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='libraryassociation',
            name='workflow_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_manager.workflowrun'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_manager.payload')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_manager.workflowrun')),
            ],
            options={
                'unique_together': {('workflow_run', 'status', 'timestamp')},
            },
        ),
    ]
