# Generated by Django 5.1 on 2024-09-25 08:06

import django.core.serializers.json
import django.db.models.deletion
import workflow_manager.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisContext',
            fields=[
                ('orcabus_id', workflow_manager.fields.OrcabusIdField(max_length=30, prefix='ctx', primary_key=True, serialize=False, unique=True)),
                ('context_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('orcabus_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('library_id', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('orcabus_id', workflow_manager.fields.OrcabusIdField(max_length=30, prefix='pld', primary_key=True, serialize=False, unique=True)),
                ('payload_ref_id', models.CharField(max_length=255, unique=True)),
                ('version', models.CharField(max_length=255)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('orcabus_id', workflow_manager.fields.OrcabusIdField(max_length=30, prefix='ana', primary_key=True, serialize=False, unique=True)),
                ('analysis_name', models.CharField(max_length=255)),
                ('analysis_version', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('contexts', models.ManyToManyField(to='workflow_manager.analysiscontext')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('orcabus_id', workflow_manager.fields.OrcabusIdField(max_length=30, prefix='anr', primary_key=True, serialize=False, unique=True)),
                ('analysis_run_id', models.CharField(max_length=255, unique=True)),
                ('analysis_run_name', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_manager.analysis')),
                ('approval_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_context', to='workflow_manager.analysiscontext')),
                ('project_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_context', to='workflow_manager.analysiscontext')),
                ('libraries', models.ManyToManyField(to='workflow_manager.library')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LibraryAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_date', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_manager.library')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('orcabus_id', workflow_manager.fields.OrcabusIdField(max_length=30, prefix='wfl', primary_key=True, serialize=False, unique=True)),
                ('workflow_name', models.CharField(max_length=255)),
                ('workflow_version', models.CharField(max_length=255)),
                ('execution_engine', models.CharField(max_length=255)),
                ('execution_engine_pipeline_id', models.CharField(max_length=255)),
                ('approval_state', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('workflow_name', 'workflow_version')},
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='workflows',
            field=models.ManyToManyField(to='workflow_manager.workflow'),
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('orcabus_id', workflow_manager.fields.OrcabusIdField(max_length=30, prefix='wfr', primary_key=True, serialize=False, unique=True)),
                ('portal_run_id', models.CharField(max_length=255, unique=True)),
                ('execution_id', models.CharField(blank=True, max_length=255, null=True)),
                ('workflow_run_name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_manager.analysisrun')),
                ('libraries', models.ManyToManyField(through='workflow_manager.LibraryAssociation', to='workflow_manager.library')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_manager.workflow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='libraryassociation',
            name='workflow_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_manager.workflowrun'),
        ),
        migrations.AlterUniqueTogether(
            name='analysis',
            unique_together={('analysis_name', 'analysis_version')},
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('orcabus_id', workflow_manager.fields.OrcabusIdField(max_length=30, prefix='stt', primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_manager.payload')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_manager.workflowrun')),
            ],
            options={
                'unique_together': {('workflow_run', 'status', 'timestamp')},
            },
        ),
    ]
