# Generated by Django 5.1 on 2024-09-09 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="workflow_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="workflow_manager.workflowrun",
            ),
        ),
    ]
