# Generated by Django 5.1 on 2024-09-07 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisContext',
            fields=[
                ('orcabus_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('context_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('analysis_run_id', models.CharField(max_length=255, unique=True)),
                ('analysis_run_name', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('approval_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_context', to='workflow_manager.analysiscontext')),
                ('project_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_context', to='workflow_manager.analysiscontext')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('analysis_name', models.CharField(max_length=255)),
                ('analysis_version', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('workflows', models.ManyToManyField(to='workflow_manager.workflow')),
                ('allowed_contexts', models.ManyToManyField(to='workflow_manager.analysiscontext')),
            ],
            options={
                'unique_together': {('analysis_name', 'analysis_version')},
            },
        ),
    ]
