# Generated by Django 5.1 on 2024-10-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysiscontext',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analysiscontext',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
