# Generated by Django 5.1 on 2024-10-03 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_manager', '0002_alter_state_workflow_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='orcabus_id',
            field=models.CharField(editable=False, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_orcabus_id', message='ULID is expected to be 26 characters long', regex='^[\\w]{26}$')]),
        ),
        migrations.AlterField(
            model_name='analysiscontext',
            name='orcabus_id',
            field=models.CharField(editable=False, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_orcabus_id', message='ULID is expected to be 26 characters long', regex='^[\\w]{26}$')]),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='orcabus_id',
            field=models.CharField(editable=False, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_orcabus_id', message='ULID is expected to be 26 characters long', regex='^[\\w]{26}$')]),
        ),
        migrations.AlterField(
            model_name='library',
            name='orcabus_id',
            field=models.CharField(editable=False, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_orcabus_id', message='ULID is expected to be 26 characters long', regex='^[\\w]{26}$')]),
        ),
        migrations.AlterField(
            model_name='libraryassociation',
            name='orcabus_id',
            field=models.CharField(editable=False, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_orcabus_id', message='ULID is expected to be 26 characters long', regex='^[\\w]{26}$')]),
        ),
        migrations.AlterField(
            model_name='payload',
            name='orcabus_id',
            field=models.CharField(editable=False, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_orcabus_id', message='ULID is expected to be 26 characters long', regex='^[\\w]{26}$')]),
        ),
        migrations.AlterField(
            model_name='state',
            name='orcabus_id',
            field=models.CharField(editable=False, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_orcabus_id', message='ULID is expected to be 26 characters long', regex='^[\\w]{26}$')]),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='orcabus_id',
            field=models.CharField(editable=False, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_orcabus_id', message='ULID is expected to be 26 characters long', regex='^[\\w]{26}$')]),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='orcabus_id',
            field=models.CharField(editable=False, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_orcabus_id', message='ULID is expected to be 26 characters long', regex='^[\\w]{26}$')]),
        ),
    ]
