# Generated by Django 5.1 on 2024-09-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_manager', '0002_analysiscontext_analysisrun_analysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='allowed_contexts',
            new_name='contexts',
        ),
    ]
