# Generated by Django 5.1 on 2024-10-10 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_manager", "0002_alter_state_workflow_run"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowRunComment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("comment", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "workflow_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="workflow_manager.workflowrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
