# Generated by Django 5.1 on 2024-09-07 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_manager', '0003_rename_allowed_contexts_analysis_contexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_manager.analysis'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='libraries',
            field=models.ManyToManyField(to='workflow_manager.library'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
