# Generated by Django 5.1 on 2024-09-09 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_manager', '0004_analysisrun_analysis_analysisrun_libraries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='analysis_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_manager.analysisrun'),
        ),
    ]
