name: CI dependency container images caching reusable workflow

on:
  workflow_call:

# Actions Used (please keep this documented here as added)
#  https://github.com/marketplace/actions/checkout
#  https://github.com/marketplace/actions/cache

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Localstack
        uses: ./.github/actions/cache-image
        with:
          prefix: localstack
          image_version: 2.1
          image: public.ecr.aws/localstack/localstack

      - name: MySQL
        uses: ./.github/actions/cache-image
        with:
          prefix: mysql
          image_version: 8
          image: public.ecr.aws/docker/library/mysql

      - name: HAProxy
        uses: ./.github/actions/cache-image
        with:
          prefix: haproxy
          image_version: 2.4
          image: public.ecr.aws/docker/library/haproxy

      - name: Prism
        uses: ./.github/actions/cache-image
        with:
          prefix: prism
          image_version: 4
          image: quay.io/victorskl/prism
