name: Pull Request Build

on:
  pull_request:
    types:
      - ready_for_review
    branches:
      - main

permissions: read-all

# Actions Used (please keep this documented here as added)
#  https://github.com/marketplace/actions/checkout
#  https://github.com/marketplace/actions/setup-python
#  https://github.com/marketplace/actions/trufflehog-oss
#  https://github.com/marketplace/actions/checkout
#  https://github.com/marketplace/actions/cache
#  https://github.com/actions-rust-lang/setup-rust-toolchain

jobs:
  pre-commit-lint-security:
    runs-on: ubuntu-latest
    steps:
      - name: Print toolchain versions
        run: |
          node -v
          python3 -V
          pip3 -V
          make --version

      # TODO see whether we can leverage https://github.com/pre-commit/action
      - name: Install system-wide tools dependencies
        run: |
          pip3 install pre-commit detect-secrets black ggshield

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.34.0
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Install dependencies
        run: |
          make install

      - name: Lint and code formatting
        run: |
          make check

  test-stateless-suite:
    # codebuild project name is initiated at ./lib/bin/statelessPipelineStack (PR-290)
    # The format: `runs-on: codebuild-<project-name>-${{ github.run_id }}-${{ github.run_attempt }}`
    # https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner.html
    runs-on: codebuild-orcabus-codebuild-gh-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rust installation
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install dependencies
        run: |
          yarn install --immutable

      - run: make test-suite

  test-stateful-stack:
    # codebuild project name is initiated at ./lib/bin/statelessPipelineStack (PR-290)
    # The format: `runs-on: codebuild-<project-name>-${{ github.run_id }}-${{ github.run_attempt }}`
    # https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner.html
    runs-on: codebuild-orcabus-codebuild-gh-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          yarn install --immutable

      - run: make test-stateful

  test-stateless-stack:
    # codebuild project name is initiated at ./lib/bin/statelessPipelineStack (PR-290)
    # The format: `runs-on: codebuild-<project-name>-${{ github.run_id }}-${{ github.run_attempt }}`
    # https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner.html
    runs-on: codebuild-orcabus-codebuild-gh-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rust installation
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install dependencies
        run: |
          yarn install --immutable

      - run: make test-stateless
