name: Pull Request Build

on:
  pull_request:
    branches:
      - main

# Actions Used (please keep this documented here as added)
#  https://github.com/marketplace/actions/checkout
#  https://github.com/marketplace/actions/setup-python
#  https://github.com/marketplace/actions/trufflehog-oss
#  https://github.com/marketplace/actions/checkout
#  https://github.com/marketplace/actions/cache

jobs:
  build:
    # Default access (restricted) - https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Print toolchain versions
        run: |
          node -v
          python3 -V
          make --version

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.34.0
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Install dependencies
        run: |
          make install

      - name: Lint and code formatting
        run: |
          make check
