name: Pull Request Build

on:
  pull_request:
    branches:
      - main

# Actions Used (please keep this documented here as added)
#  https://github.com/marketplace/actions/checkout
#  https://github.com/marketplace/actions/setup-python
#  https://github.com/marketplace/actions/trufflehog-oss
#  https://github.com/marketplace/actions/checkout
#  https://github.com/marketplace/actions/cache

jobs:
  build:
    # Default access (restricted) - https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    permissions:
      contents: read

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - name: Print toolchain versions
        run: |
          node -v
          python3 -V
          make --version

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.34.0
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Localstack
        uses: ./.github/actions/cache-image
        with:
          prefix: localstack
          image_version: 2.1
          image: public.ecr.aws/localstack/localstack

      - name: MySQL
        uses: ./.github/actions/cache-image
        with:
          prefix: mysql
          image_version: 8
          image: public.ecr.aws/docker/library/mysql

      - name: HAProxy
        uses: ./.github/actions/cache-image
        with:
          prefix: haproxy
          image_version: 2.4
          image: public.ecr.aws/docker/library/haproxy

      - name: Prism
        uses: ./.github/actions/cache-image
        with:
          prefix: prism
          image_version: 4
          image: quay.io/victorskl/prism

      - name: List container images
        run: docker images

      - name: Set up compose stack
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make install

      - name: Lint and code formatting
        run: |
          make check

      - name: Run test suite
        run: |
          make test

      - name: Tear down compose stack
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml down
